// C# script that will take input from various sources and control a first person character
// Will require:
// -Camera
// -RigidBody

/**
 * FPSController.cs
 * Joe Ford
 * Created 2019-02-22
 *
 * Take input from various sources (eg, keyboard, mouse, gamepad) and control a first person character
 */

using UnityEngine;

public class FPSController : MonoBehaviour
{
  void FixedUpdate() {
  
  }
}
